name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['7']
    env:
      GIT_USER_NAME: puneetbehl
      GIT_USER_EMAIL: behlp@objectcomputing.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Extract Target Branch
        id: extract_branch
        run: |
          echo "Determining Target Branch"
          TARGET_BRANCH=`cat $GITHUB_EVENT_PATH | jq '.release.target_commitish' | sed -e 's/^"\(.*\)"$/\1/g'`
          echo $TARGET_BRANCH
          echo ::set-output name=value::${TARGET_BRANCH}
      - name: Set the current release version
        id: release_version
        run: echo ::set-output name=release_version::${GITHUB_REF:11}
      - name: Run pre-release
        uses: micronaut-projects/github-actions/pre-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish, Upload to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
        run: |
          echo "Publishing Artifacts"
          (set -x; ./gradlew bintrayUpload --no-daemon)
          (set -x; ./gradlew assemble --no-daemon)
      - name: Export Gradle Properties
        uses: micronaut-projects/github-actions/export-gradle-properties@master
      - name: Run post-release
        if: success()
        uses: micronaut-projects/github-actions/post-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          SNAPSHOT_SUFFIX: .BUILD-SNAPSHOT
      - name: Create Message for the GORM Documentation Release
        if: success()
        id: gorm_docs_release_message
        run: |
          echo ::set-output name=value::{\"gorm_version\":\"$RELEASE_VERSION\"}
        env:
          RELEASE_VERSION: ${{ steps.release_version.outputs.release_version }}
      - name: Invoke gorm-docs release workflow
        if: success()
        id: gorm_docs
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Release
          repo: grails/gorm-docs
          ref: ${{ steps.extract_branch.outputs.value }}
          token: ${{ secrets.GH_TOKEN }}
          inputs: ${{ steps.gorm_docs_release_message.outputs.value }}
      - name: Create Message for the Maven Central Sync
        if: success()
        id: maven_sync_message
        run: |
          echo ::set-output name=value::{\"release_version\":\"$RELEASE_VERSION\"}
        env:
          RELEASE_VERSION: ${{ steps.release_version.outputs.release_version }}
      - name: Invoke the Maven Central Sync workflow
        if: success()
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Maven Central Sync
          ref: ${{ steps.extract_branch.outputs.value }}
          token: ${{ secrets.GH_TOKEN }}
          inputs: ${{ steps.maven_sync_message.outputs.value }}
